services:
  db:
    image: mysql:8.0
    container_name: finance-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: finance-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: finance
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "127.0.0.1:8888:8000"
    volumes:
      - ./app:/app/app:rw

volumes:
  dbdata: