apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
stringData:
  MYSQL_ROOT_PASSWORD: examplepassword
  MYSQL_DATABASE: exampledb
  MYSQL_USER: root
  MYSQL_PASSWORD: examplepassword
