apiVersion: v1
kind: Service
metadata:
  name: api-financeira-microservico
spec:
  selector:
    app: api-financeira-microservico
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
